// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/tt/ocean/proto/message.proto

package com.tt.ocean.proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tt.ocean.proto.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required int64 req_id = 2;</code>
     */
    boolean hasReqId();
    /**
     * <code>required int64 req_id = 2;</code>
     */
    long getReqId();

    /**
     * <code>optional int64 rsp_id = 3;</code>
     */
    boolean hasRspId();
    /**
     * <code>optional int64 rsp_id = 3;</code>
     */
    long getRspId();

    /**
     * <code>optional int64 prs_id = 4;</code>
     */
    boolean hasPrsId();
    /**
     * <code>optional int64 prs_id = 4;</code>
     */
    long getPrsId();

    /**
     * <code>optional int32 piece_id = 5;</code>
     */
    boolean hasPieceId();
    /**
     * <code>optional int32 piece_id = 5;</code>
     */
    int getPieceId();
  }
  /**
   * Protobuf type {@code com.tt.ocean.proto.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tt.ocean.proto.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      version_ = 0;
      reqId_ = 0L;
      rspId_ = 0L;
      prsId_ = 0L;
      pieceId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reqId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rspId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              prsId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pieceId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tt.ocean.proto.MessageProto.Header.class, com.tt.ocean.proto.MessageProto.Header.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int REQ_ID_FIELD_NUMBER = 2;
    private long reqId_;
    /**
     * <code>required int64 req_id = 2;</code>
     */
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 req_id = 2;</code>
     */
    public long getReqId() {
      return reqId_;
    }

    public static final int RSP_ID_FIELD_NUMBER = 3;
    private long rspId_;
    /**
     * <code>optional int64 rsp_id = 3;</code>
     */
    public boolean hasRspId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 rsp_id = 3;</code>
     */
    public long getRspId() {
      return rspId_;
    }

    public static final int PRS_ID_FIELD_NUMBER = 4;
    private long prsId_;
    /**
     * <code>optional int64 prs_id = 4;</code>
     */
    public boolean hasPrsId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 prs_id = 4;</code>
     */
    public long getPrsId() {
      return prsId_;
    }

    public static final int PIECE_ID_FIELD_NUMBER = 5;
    private int pieceId_;
    /**
     * <code>optional int32 piece_id = 5;</code>
     */
    public boolean hasPieceId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 piece_id = 5;</code>
     */
    public int getPieceId() {
      return pieceId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, reqId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, rspId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, prsId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, pieceId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, reqId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rspId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, prsId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pieceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tt.ocean.proto.MessageProto.Header)) {
        return super.equals(obj);
      }
      com.tt.ocean.proto.MessageProto.Header other = (com.tt.ocean.proto.MessageProto.Header) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasReqId() == other.hasReqId());
      if (hasReqId()) {
        result = result && (getReqId()
            == other.getReqId());
      }
      result = result && (hasRspId() == other.hasRspId());
      if (hasRspId()) {
        result = result && (getRspId()
            == other.getRspId());
      }
      result = result && (hasPrsId() == other.hasPrsId());
      if (hasPrsId()) {
        result = result && (getPrsId()
            == other.getPrsId());
      }
      result = result && (hasPieceId() == other.hasPieceId());
      if (hasPieceId()) {
        result = result && (getPieceId()
            == other.getPieceId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasReqId()) {
        hash = (37 * hash) + REQ_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getReqId());
      }
      if (hasRspId()) {
        hash = (37 * hash) + RSP_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRspId());
      }
      if (hasPrsId()) {
        hash = (37 * hash) + PRS_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPrsId());
      }
      if (hasPieceId()) {
        hash = (37 * hash) + PIECE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPieceId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.MessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tt.ocean.proto.MessageProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tt.ocean.proto.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tt.ocean.proto.Header)
        com.tt.ocean.proto.MessageProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tt.ocean.proto.MessageProto.Header.class, com.tt.ocean.proto.MessageProto.Header.Builder.class);
      }

      // Construct using com.tt.ocean.proto.MessageProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        rspId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        prsId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        pieceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_Header_descriptor;
      }

      public com.tt.ocean.proto.MessageProto.Header getDefaultInstanceForType() {
        return com.tt.ocean.proto.MessageProto.Header.getDefaultInstance();
      }

      public com.tt.ocean.proto.MessageProto.Header build() {
        com.tt.ocean.proto.MessageProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tt.ocean.proto.MessageProto.Header buildPartial() {
        com.tt.ocean.proto.MessageProto.Header result = new com.tt.ocean.proto.MessageProto.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqId_ = reqId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rspId_ = rspId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prsId_ = prsId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pieceId_ = pieceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tt.ocean.proto.MessageProto.Header) {
          return mergeFrom((com.tt.ocean.proto.MessageProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tt.ocean.proto.MessageProto.Header other) {
        if (other == com.tt.ocean.proto.MessageProto.Header.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasReqId()) {
          setReqId(other.getReqId());
        }
        if (other.hasRspId()) {
          setRspId(other.getRspId());
        }
        if (other.hasPrsId()) {
          setPrsId(other.getPrsId());
        }
        if (other.hasPieceId()) {
          setPieceId(other.getPieceId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasReqId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tt.ocean.proto.MessageProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tt.ocean.proto.MessageProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long reqId_ ;
      /**
       * <code>required int64 req_id = 2;</code>
       */
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 req_id = 2;</code>
       */
      public long getReqId() {
        return reqId_;
      }
      /**
       * <code>required int64 req_id = 2;</code>
       */
      public Builder setReqId(long value) {
        bitField0_ |= 0x00000002;
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 req_id = 2;</code>
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqId_ = 0L;
        onChanged();
        return this;
      }

      private long rspId_ ;
      /**
       * <code>optional int64 rsp_id = 3;</code>
       */
      public boolean hasRspId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 rsp_id = 3;</code>
       */
      public long getRspId() {
        return rspId_;
      }
      /**
       * <code>optional int64 rsp_id = 3;</code>
       */
      public Builder setRspId(long value) {
        bitField0_ |= 0x00000004;
        rspId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rsp_id = 3;</code>
       */
      public Builder clearRspId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rspId_ = 0L;
        onChanged();
        return this;
      }

      private long prsId_ ;
      /**
       * <code>optional int64 prs_id = 4;</code>
       */
      public boolean hasPrsId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 prs_id = 4;</code>
       */
      public long getPrsId() {
        return prsId_;
      }
      /**
       * <code>optional int64 prs_id = 4;</code>
       */
      public Builder setPrsId(long value) {
        bitField0_ |= 0x00000008;
        prsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 prs_id = 4;</code>
       */
      public Builder clearPrsId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prsId_ = 0L;
        onChanged();
        return this;
      }

      private int pieceId_ ;
      /**
       * <code>optional int32 piece_id = 5;</code>
       */
      public boolean hasPieceId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 piece_id = 5;</code>
       */
      public int getPieceId() {
        return pieceId_;
      }
      /**
       * <code>optional int32 piece_id = 5;</code>
       */
      public Builder setPieceId(int value) {
        bitField0_ |= 0x00000010;
        pieceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 piece_id = 5;</code>
       */
      public Builder clearPieceId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pieceId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tt.ocean.proto.Header)
    }

    // @@protoc_insertion_point(class_scope:com.tt.ocean.proto.Header)
    private static final com.tt.ocean.proto.MessageProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tt.ocean.proto.MessageProto.Header();
    }

    public static com.tt.ocean.proto.MessageProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    public com.tt.ocean.proto.MessageProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartbeatReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tt.ocean.proto.HeartbeatReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string my_type = 1;</code>
     */
    boolean hasMyType();
    /**
     * <code>optional string my_type = 1;</code>
     */
    java.lang.String getMyType();
    /**
     * <code>optional string my_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getMyTypeBytes();

    /**
     * <code>optional int64 cpu_id = 2;</code>
     */
    boolean hasCpuId();
    /**
     * <code>optional int64 cpu_id = 2;</code>
     */
    long getCpuId();

    /**
     * <code>optional double cpu_rate = 3;</code>
     */
    boolean hasCpuRate();
    /**
     * <code>optional double cpu_rate = 3;</code>
     */
    double getCpuRate();

    /**
     * <code>optional int64 memory = 4;</code>
     */
    boolean hasMemory();
    /**
     * <code>optional int64 memory = 4;</code>
     */
    long getMemory();

    /**
     * <code>optional int64 process_id = 5;</code>
     */
    boolean hasProcessId();
    /**
     * <code>optional int64 process_id = 5;</code>
     */
    long getProcessId();

    /**
     * <code>optional int64 piece_id = 6;</code>
     */
    boolean hasPieceId();
    /**
     * <code>optional int64 piece_id = 6;</code>
     */
    long getPieceId();
  }
  /**
   * Protobuf type {@code com.tt.ocean.proto.HeartbeatReq}
   */
  public  static final class HeartbeatReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tt.ocean.proto.HeartbeatReq)
      HeartbeatReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartbeatReq.newBuilder() to construct.
    private HeartbeatReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartbeatReq() {
      myType_ = "";
      cpuId_ = 0L;
      cpuRate_ = 0D;
      memory_ = 0L;
      processId_ = 0L;
      pieceId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeatReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              myType_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cpuId_ = input.readInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              cpuRate_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              memory_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              processId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              pieceId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_HeartbeatReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_HeartbeatReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tt.ocean.proto.MessageProto.HeartbeatReq.class, com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder.class);
    }

    private int bitField0_;
    public static final int MY_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object myType_;
    /**
     * <code>optional string my_type = 1;</code>
     */
    public boolean hasMyType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string my_type = 1;</code>
     */
    public java.lang.String getMyType() {
      java.lang.Object ref = myType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          myType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string my_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMyTypeBytes() {
      java.lang.Object ref = myType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_ID_FIELD_NUMBER = 2;
    private long cpuId_;
    /**
     * <code>optional int64 cpu_id = 2;</code>
     */
    public boolean hasCpuId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 cpu_id = 2;</code>
     */
    public long getCpuId() {
      return cpuId_;
    }

    public static final int CPU_RATE_FIELD_NUMBER = 3;
    private double cpuRate_;
    /**
     * <code>optional double cpu_rate = 3;</code>
     */
    public boolean hasCpuRate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double cpu_rate = 3;</code>
     */
    public double getCpuRate() {
      return cpuRate_;
    }

    public static final int MEMORY_FIELD_NUMBER = 4;
    private long memory_;
    /**
     * <code>optional int64 memory = 4;</code>
     */
    public boolean hasMemory() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 memory = 4;</code>
     */
    public long getMemory() {
      return memory_;
    }

    public static final int PROCESS_ID_FIELD_NUMBER = 5;
    private long processId_;
    /**
     * <code>optional int64 process_id = 5;</code>
     */
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 process_id = 5;</code>
     */
    public long getProcessId() {
      return processId_;
    }

    public static final int PIECE_ID_FIELD_NUMBER = 6;
    private long pieceId_;
    /**
     * <code>optional int64 piece_id = 6;</code>
     */
    public boolean hasPieceId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 piece_id = 6;</code>
     */
    public long getPieceId() {
      return pieceId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, myType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, cpuId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, cpuRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, memory_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, processId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, pieceId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, myType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cpuId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, cpuRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, memory_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, processId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, pieceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tt.ocean.proto.MessageProto.HeartbeatReq)) {
        return super.equals(obj);
      }
      com.tt.ocean.proto.MessageProto.HeartbeatReq other = (com.tt.ocean.proto.MessageProto.HeartbeatReq) obj;

      boolean result = true;
      result = result && (hasMyType() == other.hasMyType());
      if (hasMyType()) {
        result = result && getMyType()
            .equals(other.getMyType());
      }
      result = result && (hasCpuId() == other.hasCpuId());
      if (hasCpuId()) {
        result = result && (getCpuId()
            == other.getCpuId());
      }
      result = result && (hasCpuRate() == other.hasCpuRate());
      if (hasCpuRate()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getCpuRate())
            == java.lang.Double.doubleToLongBits(
                other.getCpuRate()));
      }
      result = result && (hasMemory() == other.hasMemory());
      if (hasMemory()) {
        result = result && (getMemory()
            == other.getMemory());
      }
      result = result && (hasProcessId() == other.hasProcessId());
      if (hasProcessId()) {
        result = result && (getProcessId()
            == other.getProcessId());
      }
      result = result && (hasPieceId() == other.hasPieceId());
      if (hasPieceId()) {
        result = result && (getPieceId()
            == other.getPieceId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMyType()) {
        hash = (37 * hash) + MY_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMyType().hashCode();
      }
      if (hasCpuId()) {
        hash = (37 * hash) + CPU_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCpuId());
      }
      if (hasCpuRate()) {
        hash = (37 * hash) + CPU_RATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCpuRate()));
      }
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMemory());
      }
      if (hasProcessId()) {
        hash = (37 * hash) + PROCESS_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getProcessId());
      }
      if (hasPieceId()) {
        hash = (37 * hash) + PIECE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPieceId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.MessageProto.HeartbeatReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tt.ocean.proto.MessageProto.HeartbeatReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tt.ocean.proto.HeartbeatReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tt.ocean.proto.HeartbeatReq)
        com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_HeartbeatReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_HeartbeatReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tt.ocean.proto.MessageProto.HeartbeatReq.class, com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder.class);
      }

      // Construct using com.tt.ocean.proto.MessageProto.HeartbeatReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        myType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cpuId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        cpuRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        memory_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        processId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        pieceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tt.ocean.proto.MessageProto.internal_static_com_tt_ocean_proto_HeartbeatReq_descriptor;
      }

      public com.tt.ocean.proto.MessageProto.HeartbeatReq getDefaultInstanceForType() {
        return com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance();
      }

      public com.tt.ocean.proto.MessageProto.HeartbeatReq build() {
        com.tt.ocean.proto.MessageProto.HeartbeatReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tt.ocean.proto.MessageProto.HeartbeatReq buildPartial() {
        com.tt.ocean.proto.MessageProto.HeartbeatReq result = new com.tt.ocean.proto.MessageProto.HeartbeatReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.myType_ = myType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cpuId_ = cpuId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cpuRate_ = cpuRate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.memory_ = memory_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.processId_ = processId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pieceId_ = pieceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tt.ocean.proto.MessageProto.HeartbeatReq) {
          return mergeFrom((com.tt.ocean.proto.MessageProto.HeartbeatReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tt.ocean.proto.MessageProto.HeartbeatReq other) {
        if (other == com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance()) return this;
        if (other.hasMyType()) {
          bitField0_ |= 0x00000001;
          myType_ = other.myType_;
          onChanged();
        }
        if (other.hasCpuId()) {
          setCpuId(other.getCpuId());
        }
        if (other.hasCpuRate()) {
          setCpuRate(other.getCpuRate());
        }
        if (other.hasMemory()) {
          setMemory(other.getMemory());
        }
        if (other.hasProcessId()) {
          setProcessId(other.getProcessId());
        }
        if (other.hasPieceId()) {
          setPieceId(other.getPieceId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tt.ocean.proto.MessageProto.HeartbeatReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tt.ocean.proto.MessageProto.HeartbeatReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object myType_ = "";
      /**
       * <code>optional string my_type = 1;</code>
       */
      public boolean hasMyType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string my_type = 1;</code>
       */
      public java.lang.String getMyType() {
        java.lang.Object ref = myType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            myType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string my_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMyTypeBytes() {
        java.lang.Object ref = myType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          myType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string my_type = 1;</code>
       */
      public Builder setMyType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        myType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string my_type = 1;</code>
       */
      public Builder clearMyType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        myType_ = getDefaultInstance().getMyType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string my_type = 1;</code>
       */
      public Builder setMyTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        myType_ = value;
        onChanged();
        return this;
      }

      private long cpuId_ ;
      /**
       * <code>optional int64 cpu_id = 2;</code>
       */
      public boolean hasCpuId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 cpu_id = 2;</code>
       */
      public long getCpuId() {
        return cpuId_;
      }
      /**
       * <code>optional int64 cpu_id = 2;</code>
       */
      public Builder setCpuId(long value) {
        bitField0_ |= 0x00000002;
        cpuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cpu_id = 2;</code>
       */
      public Builder clearCpuId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cpuId_ = 0L;
        onChanged();
        return this;
      }

      private double cpuRate_ ;
      /**
       * <code>optional double cpu_rate = 3;</code>
       */
      public boolean hasCpuRate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double cpu_rate = 3;</code>
       */
      public double getCpuRate() {
        return cpuRate_;
      }
      /**
       * <code>optional double cpu_rate = 3;</code>
       */
      public Builder setCpuRate(double value) {
        bitField0_ |= 0x00000004;
        cpuRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double cpu_rate = 3;</code>
       */
      public Builder clearCpuRate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cpuRate_ = 0D;
        onChanged();
        return this;
      }

      private long memory_ ;
      /**
       * <code>optional int64 memory = 4;</code>
       */
      public boolean hasMemory() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 memory = 4;</code>
       */
      public long getMemory() {
        return memory_;
      }
      /**
       * <code>optional int64 memory = 4;</code>
       */
      public Builder setMemory(long value) {
        bitField0_ |= 0x00000008;
        memory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 memory = 4;</code>
       */
      public Builder clearMemory() {
        bitField0_ = (bitField0_ & ~0x00000008);
        memory_ = 0L;
        onChanged();
        return this;
      }

      private long processId_ ;
      /**
       * <code>optional int64 process_id = 5;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 process_id = 5;</code>
       */
      public long getProcessId() {
        return processId_;
      }
      /**
       * <code>optional int64 process_id = 5;</code>
       */
      public Builder setProcessId(long value) {
        bitField0_ |= 0x00000010;
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 process_id = 5;</code>
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        processId_ = 0L;
        onChanged();
        return this;
      }

      private long pieceId_ ;
      /**
       * <code>optional int64 piece_id = 6;</code>
       */
      public boolean hasPieceId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 piece_id = 6;</code>
       */
      public long getPieceId() {
        return pieceId_;
      }
      /**
       * <code>optional int64 piece_id = 6;</code>
       */
      public Builder setPieceId(long value) {
        bitField0_ |= 0x00000020;
        pieceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 piece_id = 6;</code>
       */
      public Builder clearPieceId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pieceId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tt.ocean.proto.HeartbeatReq)
    }

    // @@protoc_insertion_point(class_scope:com.tt.ocean.proto.HeartbeatReq)
    private static final com.tt.ocean.proto.MessageProto.HeartbeatReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tt.ocean.proto.MessageProto.HeartbeatReq();
    }

    public static com.tt.ocean.proto.MessageProto.HeartbeatReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartbeatReq>
        PARSER = new com.google.protobuf.AbstractParser<HeartbeatReq>() {
      public HeartbeatReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeatReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartbeatReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeatReq> getParserForType() {
      return PARSER;
    }

    public com.tt.ocean.proto.MessageProto.HeartbeatReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tt_ocean_proto_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tt_ocean_proto_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tt_ocean_proto_HeartbeatReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tt_ocean_proto_HeartbeatReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n com/tt/ocean/proto/message.proto\022\022com." +
      "tt.ocean.proto\"[\n\006Header\022\017\n\007version\030\001 \002(" +
      "\005\022\016\n\006req_id\030\002 \002(\003\022\016\n\006rsp_id\030\003 \001(\003\022\016\n\006prs" +
      "_id\030\004 \001(\003\022\020\n\010piece_id\030\005 \001(\005\"w\n\014Heartbeat" +
      "Req\022\017\n\007my_type\030\001 \001(\t\022\016\n\006cpu_id\030\002 \001(\003\022\020\n\010" +
      "cpu_rate\030\003 \001(\001\022\016\n\006memory\030\004 \001(\003\022\022\n\nproces" +
      "s_id\030\005 \001(\003\022\020\n\010piece_id\030\006 \001(\003B\"\n\022com.tt.o" +
      "cean.protoB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tt_ocean_proto_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tt_ocean_proto_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tt_ocean_proto_Header_descriptor,
        new java.lang.String[] { "Version", "ReqId", "RspId", "PrsId", "PieceId", });
    internal_static_com_tt_ocean_proto_HeartbeatReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tt_ocean_proto_HeartbeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tt_ocean_proto_HeartbeatReq_descriptor,
        new java.lang.String[] { "MyType", "CpuId", "CpuRate", "Memory", "ProcessId", "PieceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
