// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocean.proto

package com.tt.ocean.proto;

public final class OceanProto {
  private OceanProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OceanMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tt.ocean.proto.OceanMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.tt.ocean.proto.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .com.tt.ocean.proto.Header header = 1;</code>
     */
    com.tt.ocean.proto.MessageProto.Header getHeader();
    /**
     * <code>required .com.tt.ocean.proto.Header header = 1;</code>
     */
    com.tt.ocean.proto.MessageProto.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
     */
    com.tt.ocean.proto.MessageProto.HeartbeatReq getHeartbeat();
    /**
     * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
     */
    com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder getHeartbeatOrBuilder();

    /**
     * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
     */
    boolean hasConfigRequest();
    /**
     * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
     */
    com.tt.ocean.proto.ConfigProto.ConfigRequest getConfigRequest();
    /**
     * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
     */
    com.tt.ocean.proto.ConfigProto.ConfigRequestOrBuilder getConfigRequestOrBuilder();

    /**
     * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
     */
    boolean hasConfigResponse();
    /**
     * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
     */
    com.tt.ocean.proto.ConfigProto.ConfigResponse getConfigResponse();
    /**
     * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
     */
    com.tt.ocean.proto.ConfigProto.ConfigResponseOrBuilder getConfigResponseOrBuilder();

    /**
     * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
     */
    boolean hasNodeRequest();
    /**
     * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
     */
    com.tt.ocean.proto.NodeProto.NodeRequest getNodeRequest();
    /**
     * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
     */
    com.tt.ocean.proto.NodeProto.NodeRequestOrBuilder getNodeRequestOrBuilder();

    /**
     * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
     */
    boolean hasNodeResponse();
    /**
     * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
     */
    com.tt.ocean.proto.NodeProto.NodeResponse getNodeResponse();
    /**
     * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
     */
    com.tt.ocean.proto.NodeProto.NodeResponseOrBuilder getNodeResponseOrBuilder();
  }
  /**
   * Protobuf type {@code com.tt.ocean.proto.OceanMessage}
   */
  public  static final class OceanMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tt.ocean.proto.OceanMessage)
      OceanMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OceanMessage.newBuilder() to construct.
    private OceanMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OceanMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OceanMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.tt.ocean.proto.MessageProto.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.tt.ocean.proto.MessageProto.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.tt.ocean.proto.ConfigProto.ConfigRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = configRequest_.toBuilder();
              }
              configRequest_ = input.readMessage(com.tt.ocean.proto.ConfigProto.ConfigRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(configRequest_);
                configRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 26: {
              com.tt.ocean.proto.ConfigProto.ConfigResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = configResponse_.toBuilder();
              }
              configResponse_ = input.readMessage(com.tt.ocean.proto.ConfigProto.ConfigResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(configResponse_);
                configResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 34: {
              com.tt.ocean.proto.NodeProto.NodeRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = nodeRequest_.toBuilder();
              }
              nodeRequest_ = input.readMessage(com.tt.ocean.proto.NodeProto.NodeRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nodeRequest_);
                nodeRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 42: {
              com.tt.ocean.proto.NodeProto.NodeResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = nodeResponse_.toBuilder();
              }
              nodeResponse_ = input.readMessage(com.tt.ocean.proto.NodeProto.NodeResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nodeResponse_);
                nodeResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 50: {
              com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = heartbeat_.toBuilder();
              }
              heartbeat_ = input.readMessage(com.tt.ocean.proto.MessageProto.HeartbeatReq.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartbeat_);
                heartbeat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tt.ocean.proto.OceanProto.internal_static_com_tt_ocean_proto_OceanMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tt.ocean.proto.OceanProto.internal_static_com_tt_ocean_proto_OceanMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tt.ocean.proto.OceanProto.OceanMessage.class, com.tt.ocean.proto.OceanProto.OceanMessage.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.tt.ocean.proto.MessageProto.Header header_;
    /**
     * <code>required .com.tt.ocean.proto.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.tt.ocean.proto.Header header = 1;</code>
     */
    public com.tt.ocean.proto.MessageProto.Header getHeader() {
      return header_ == null ? com.tt.ocean.proto.MessageProto.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>required .com.tt.ocean.proto.Header header = 1;</code>
     */
    public com.tt.ocean.proto.MessageProto.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? com.tt.ocean.proto.MessageProto.Header.getDefaultInstance() : header_;
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 6;
    private com.tt.ocean.proto.MessageProto.HeartbeatReq heartbeat_;
    /**
     * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
     */
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
     */
    public com.tt.ocean.proto.MessageProto.HeartbeatReq getHeartbeat() {
      return heartbeat_ == null ? com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance() : heartbeat_;
    }
    /**
     * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
     */
    public com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder getHeartbeatOrBuilder() {
      return heartbeat_ == null ? com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance() : heartbeat_;
    }

    public static final int CONFIG_REQUEST_FIELD_NUMBER = 2;
    private com.tt.ocean.proto.ConfigProto.ConfigRequest configRequest_;
    /**
     * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
     */
    public boolean hasConfigRequest() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
     */
    public com.tt.ocean.proto.ConfigProto.ConfigRequest getConfigRequest() {
      return configRequest_ == null ? com.tt.ocean.proto.ConfigProto.ConfigRequest.getDefaultInstance() : configRequest_;
    }
    /**
     * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
     */
    public com.tt.ocean.proto.ConfigProto.ConfigRequestOrBuilder getConfigRequestOrBuilder() {
      return configRequest_ == null ? com.tt.ocean.proto.ConfigProto.ConfigRequest.getDefaultInstance() : configRequest_;
    }

    public static final int CONFIG_RESPONSE_FIELD_NUMBER = 3;
    private com.tt.ocean.proto.ConfigProto.ConfigResponse configResponse_;
    /**
     * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
     */
    public boolean hasConfigResponse() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
     */
    public com.tt.ocean.proto.ConfigProto.ConfigResponse getConfigResponse() {
      return configResponse_ == null ? com.tt.ocean.proto.ConfigProto.ConfigResponse.getDefaultInstance() : configResponse_;
    }
    /**
     * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
     */
    public com.tt.ocean.proto.ConfigProto.ConfigResponseOrBuilder getConfigResponseOrBuilder() {
      return configResponse_ == null ? com.tt.ocean.proto.ConfigProto.ConfigResponse.getDefaultInstance() : configResponse_;
    }

    public static final int NODE_REQUEST_FIELD_NUMBER = 4;
    private com.tt.ocean.proto.NodeProto.NodeRequest nodeRequest_;
    /**
     * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
     */
    public boolean hasNodeRequest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
     */
    public com.tt.ocean.proto.NodeProto.NodeRequest getNodeRequest() {
      return nodeRequest_ == null ? com.tt.ocean.proto.NodeProto.NodeRequest.getDefaultInstance() : nodeRequest_;
    }
    /**
     * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
     */
    public com.tt.ocean.proto.NodeProto.NodeRequestOrBuilder getNodeRequestOrBuilder() {
      return nodeRequest_ == null ? com.tt.ocean.proto.NodeProto.NodeRequest.getDefaultInstance() : nodeRequest_;
    }

    public static final int NODE_RESPONSE_FIELD_NUMBER = 5;
    private com.tt.ocean.proto.NodeProto.NodeResponse nodeResponse_;
    /**
     * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
     */
    public boolean hasNodeResponse() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
     */
    public com.tt.ocean.proto.NodeProto.NodeResponse getNodeResponse() {
      return nodeResponse_ == null ? com.tt.ocean.proto.NodeProto.NodeResponse.getDefaultInstance() : nodeResponse_;
    }
    /**
     * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
     */
    public com.tt.ocean.proto.NodeProto.NodeResponseOrBuilder getNodeResponseOrBuilder() {
      return nodeResponse_ == null ? com.tt.ocean.proto.NodeProto.NodeResponse.getDefaultInstance() : nodeResponse_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasConfigRequest()) {
        if (!getConfigRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasConfigResponse()) {
        if (!getConfigResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasNodeRequest()) {
        if (!getNodeRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasNodeResponse()) {
        if (!getNodeResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getHeader());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(2, getConfigRequest());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(3, getConfigResponse());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(4, getNodeRequest());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(5, getNodeResponse());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(6, getHeartbeat());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConfigRequest());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getConfigResponse());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNodeRequest());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getNodeResponse());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getHeartbeat());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tt.ocean.proto.OceanProto.OceanMessage)) {
        return super.equals(obj);
      }
      com.tt.ocean.proto.OceanProto.OceanMessage other = (com.tt.ocean.proto.OceanProto.OceanMessage) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasHeartbeat() == other.hasHeartbeat());
      if (hasHeartbeat()) {
        result = result && getHeartbeat()
            .equals(other.getHeartbeat());
      }
      result = result && (hasConfigRequest() == other.hasConfigRequest());
      if (hasConfigRequest()) {
        result = result && getConfigRequest()
            .equals(other.getConfigRequest());
      }
      result = result && (hasConfigResponse() == other.hasConfigResponse());
      if (hasConfigResponse()) {
        result = result && getConfigResponse()
            .equals(other.getConfigResponse());
      }
      result = result && (hasNodeRequest() == other.hasNodeRequest());
      if (hasNodeRequest()) {
        result = result && getNodeRequest()
            .equals(other.getNodeRequest());
      }
      result = result && (hasNodeResponse() == other.hasNodeResponse());
      if (hasNodeResponse()) {
        result = result && getNodeResponse()
            .equals(other.getNodeResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasHeartbeat()) {
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeat().hashCode();
      }
      if (hasConfigRequest()) {
        hash = (37 * hash) + CONFIG_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getConfigRequest().hashCode();
      }
      if (hasConfigResponse()) {
        hash = (37 * hash) + CONFIG_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getConfigResponse().hashCode();
      }
      if (hasNodeRequest()) {
        hash = (37 * hash) + NODE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getNodeRequest().hashCode();
      }
      if (hasNodeResponse()) {
        hash = (37 * hash) + NODE_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getNodeResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tt.ocean.proto.OceanProto.OceanMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tt.ocean.proto.OceanProto.OceanMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tt.ocean.proto.OceanMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tt.ocean.proto.OceanMessage)
        com.tt.ocean.proto.OceanProto.OceanMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tt.ocean.proto.OceanProto.internal_static_com_tt_ocean_proto_OceanMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tt.ocean.proto.OceanProto.internal_static_com_tt_ocean_proto_OceanMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tt.ocean.proto.OceanProto.OceanMessage.class, com.tt.ocean.proto.OceanProto.OceanMessage.Builder.class);
      }

      // Construct using com.tt.ocean.proto.OceanProto.OceanMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getHeartbeatFieldBuilder();
          getConfigRequestFieldBuilder();
          getConfigResponseFieldBuilder();
          getNodeRequestFieldBuilder();
          getNodeResponseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (heartbeatBuilder_ == null) {
          heartbeat_ = null;
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (configRequestBuilder_ == null) {
          configRequest_ = null;
        } else {
          configRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (configResponseBuilder_ == null) {
          configResponse_ = null;
        } else {
          configResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (nodeRequestBuilder_ == null) {
          nodeRequest_ = null;
        } else {
          nodeRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (nodeResponseBuilder_ == null) {
          nodeResponse_ = null;
        } else {
          nodeResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tt.ocean.proto.OceanProto.internal_static_com_tt_ocean_proto_OceanMessage_descriptor;
      }

      public com.tt.ocean.proto.OceanProto.OceanMessage getDefaultInstanceForType() {
        return com.tt.ocean.proto.OceanProto.OceanMessage.getDefaultInstance();
      }

      public com.tt.ocean.proto.OceanProto.OceanMessage build() {
        com.tt.ocean.proto.OceanProto.OceanMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tt.ocean.proto.OceanProto.OceanMessage buildPartial() {
        com.tt.ocean.proto.OceanProto.OceanMessage result = new com.tt.ocean.proto.OceanProto.OceanMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (heartbeatBuilder_ == null) {
          result.heartbeat_ = heartbeat_;
        } else {
          result.heartbeat_ = heartbeatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (configRequestBuilder_ == null) {
          result.configRequest_ = configRequest_;
        } else {
          result.configRequest_ = configRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (configResponseBuilder_ == null) {
          result.configResponse_ = configResponse_;
        } else {
          result.configResponse_ = configResponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (nodeRequestBuilder_ == null) {
          result.nodeRequest_ = nodeRequest_;
        } else {
          result.nodeRequest_ = nodeRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (nodeResponseBuilder_ == null) {
          result.nodeResponse_ = nodeResponse_;
        } else {
          result.nodeResponse_ = nodeResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tt.ocean.proto.OceanProto.OceanMessage) {
          return mergeFrom((com.tt.ocean.proto.OceanProto.OceanMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tt.ocean.proto.OceanProto.OceanMessage other) {
        if (other == com.tt.ocean.proto.OceanProto.OceanMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasHeartbeat()) {
          mergeHeartbeat(other.getHeartbeat());
        }
        if (other.hasConfigRequest()) {
          mergeConfigRequest(other.getConfigRequest());
        }
        if (other.hasConfigResponse()) {
          mergeConfigResponse(other.getConfigResponse());
        }
        if (other.hasNodeRequest()) {
          mergeNodeRequest(other.getNodeRequest());
        }
        if (other.hasNodeResponse()) {
          mergeNodeResponse(other.getNodeResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          return false;
        }
        if (!getHeader().isInitialized()) {
          return false;
        }
        if (hasConfigRequest()) {
          if (!getConfigRequest().isInitialized()) {
            return false;
          }
        }
        if (hasConfigResponse()) {
          if (!getConfigResponse().isInitialized()) {
            return false;
          }
        }
        if (hasNodeRequest()) {
          if (!getNodeRequest().isInitialized()) {
            return false;
          }
        }
        if (hasNodeResponse()) {
          if (!getNodeResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tt.ocean.proto.OceanProto.OceanMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tt.ocean.proto.OceanProto.OceanMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.tt.ocean.proto.MessageProto.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.MessageProto.Header, com.tt.ocean.proto.MessageProto.Header.Builder, com.tt.ocean.proto.MessageProto.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public com.tt.ocean.proto.MessageProto.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.tt.ocean.proto.MessageProto.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public Builder setHeader(com.tt.ocean.proto.MessageProto.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public Builder setHeader(
          com.tt.ocean.proto.MessageProto.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public Builder mergeHeader(com.tt.ocean.proto.MessageProto.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != null &&
              header_ != com.tt.ocean.proto.MessageProto.Header.getDefaultInstance()) {
            header_ =
              com.tt.ocean.proto.MessageProto.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public com.tt.ocean.proto.MessageProto.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      public com.tt.ocean.proto.MessageProto.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.tt.ocean.proto.MessageProto.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>required .com.tt.ocean.proto.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.MessageProto.Header, com.tt.ocean.proto.MessageProto.Header.Builder, com.tt.ocean.proto.MessageProto.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tt.ocean.proto.MessageProto.Header, com.tt.ocean.proto.MessageProto.Header.Builder, com.tt.ocean.proto.MessageProto.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.tt.ocean.proto.MessageProto.HeartbeatReq heartbeat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.MessageProto.HeartbeatReq, com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder, com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public com.tt.ocean.proto.MessageProto.HeartbeatReq getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          return heartbeat_ == null ? com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance() : heartbeat_;
        } else {
          return heartbeatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public Builder setHeartbeat(com.tt.ocean.proto.MessageProto.HeartbeatReq value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeat_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public Builder setHeartbeat(
          com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public Builder mergeHeartbeat(com.tt.ocean.proto.MessageProto.HeartbeatReq value) {
        if (heartbeatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              heartbeat_ != null &&
              heartbeat_ != com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance()) {
            heartbeat_ =
              com.tt.ocean.proto.MessageProto.HeartbeatReq.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
          } else {
            heartbeat_ = value;
          }
          onChanged();
        } else {
          heartbeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = null;
          onChanged();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder getHeartbeatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      public com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder getHeartbeatOrBuilder() {
        if (heartbeatBuilder_ != null) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          return heartbeat_ == null ?
              com.tt.ocean.proto.MessageProto.HeartbeatReq.getDefaultInstance() : heartbeat_;
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.HeartbeatReq heartbeat = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.MessageProto.HeartbeatReq, com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder, com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tt.ocean.proto.MessageProto.HeartbeatReq, com.tt.ocean.proto.MessageProto.HeartbeatReq.Builder, com.tt.ocean.proto.MessageProto.HeartbeatReqOrBuilder>(
                  getHeartbeat(),
                  getParentForChildren(),
                  isClean());
          heartbeat_ = null;
        }
        return heartbeatBuilder_;
      }

      private com.tt.ocean.proto.ConfigProto.ConfigRequest configRequest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.ConfigProto.ConfigRequest, com.tt.ocean.proto.ConfigProto.ConfigRequest.Builder, com.tt.ocean.proto.ConfigProto.ConfigRequestOrBuilder> configRequestBuilder_;
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public boolean hasConfigRequest() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public com.tt.ocean.proto.ConfigProto.ConfigRequest getConfigRequest() {
        if (configRequestBuilder_ == null) {
          return configRequest_ == null ? com.tt.ocean.proto.ConfigProto.ConfigRequest.getDefaultInstance() : configRequest_;
        } else {
          return configRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public Builder setConfigRequest(com.tt.ocean.proto.ConfigProto.ConfigRequest value) {
        if (configRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          configRequest_ = value;
          onChanged();
        } else {
          configRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public Builder setConfigRequest(
          com.tt.ocean.proto.ConfigProto.ConfigRequest.Builder builderForValue) {
        if (configRequestBuilder_ == null) {
          configRequest_ = builderForValue.build();
          onChanged();
        } else {
          configRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public Builder mergeConfigRequest(com.tt.ocean.proto.ConfigProto.ConfigRequest value) {
        if (configRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              configRequest_ != null &&
              configRequest_ != com.tt.ocean.proto.ConfigProto.ConfigRequest.getDefaultInstance()) {
            configRequest_ =
              com.tt.ocean.proto.ConfigProto.ConfigRequest.newBuilder(configRequest_).mergeFrom(value).buildPartial();
          } else {
            configRequest_ = value;
          }
          onChanged();
        } else {
          configRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public Builder clearConfigRequest() {
        if (configRequestBuilder_ == null) {
          configRequest_ = null;
          onChanged();
        } else {
          configRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public com.tt.ocean.proto.ConfigProto.ConfigRequest.Builder getConfigRequestBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getConfigRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      public com.tt.ocean.proto.ConfigProto.ConfigRequestOrBuilder getConfigRequestOrBuilder() {
        if (configRequestBuilder_ != null) {
          return configRequestBuilder_.getMessageOrBuilder();
        } else {
          return configRequest_ == null ?
              com.tt.ocean.proto.ConfigProto.ConfigRequest.getDefaultInstance() : configRequest_;
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigRequest config_request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.ConfigProto.ConfigRequest, com.tt.ocean.proto.ConfigProto.ConfigRequest.Builder, com.tt.ocean.proto.ConfigProto.ConfigRequestOrBuilder> 
          getConfigRequestFieldBuilder() {
        if (configRequestBuilder_ == null) {
          configRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tt.ocean.proto.ConfigProto.ConfigRequest, com.tt.ocean.proto.ConfigProto.ConfigRequest.Builder, com.tt.ocean.proto.ConfigProto.ConfigRequestOrBuilder>(
                  getConfigRequest(),
                  getParentForChildren(),
                  isClean());
          configRequest_ = null;
        }
        return configRequestBuilder_;
      }

      private com.tt.ocean.proto.ConfigProto.ConfigResponse configResponse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.ConfigProto.ConfigResponse, com.tt.ocean.proto.ConfigProto.ConfigResponse.Builder, com.tt.ocean.proto.ConfigProto.ConfigResponseOrBuilder> configResponseBuilder_;
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public boolean hasConfigResponse() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public com.tt.ocean.proto.ConfigProto.ConfigResponse getConfigResponse() {
        if (configResponseBuilder_ == null) {
          return configResponse_ == null ? com.tt.ocean.proto.ConfigProto.ConfigResponse.getDefaultInstance() : configResponse_;
        } else {
          return configResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public Builder setConfigResponse(com.tt.ocean.proto.ConfigProto.ConfigResponse value) {
        if (configResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          configResponse_ = value;
          onChanged();
        } else {
          configResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public Builder setConfigResponse(
          com.tt.ocean.proto.ConfigProto.ConfigResponse.Builder builderForValue) {
        if (configResponseBuilder_ == null) {
          configResponse_ = builderForValue.build();
          onChanged();
        } else {
          configResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public Builder mergeConfigResponse(com.tt.ocean.proto.ConfigProto.ConfigResponse value) {
        if (configResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              configResponse_ != null &&
              configResponse_ != com.tt.ocean.proto.ConfigProto.ConfigResponse.getDefaultInstance()) {
            configResponse_ =
              com.tt.ocean.proto.ConfigProto.ConfigResponse.newBuilder(configResponse_).mergeFrom(value).buildPartial();
          } else {
            configResponse_ = value;
          }
          onChanged();
        } else {
          configResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public Builder clearConfigResponse() {
        if (configResponseBuilder_ == null) {
          configResponse_ = null;
          onChanged();
        } else {
          configResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public com.tt.ocean.proto.ConfigProto.ConfigResponse.Builder getConfigResponseBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getConfigResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      public com.tt.ocean.proto.ConfigProto.ConfigResponseOrBuilder getConfigResponseOrBuilder() {
        if (configResponseBuilder_ != null) {
          return configResponseBuilder_.getMessageOrBuilder();
        } else {
          return configResponse_ == null ?
              com.tt.ocean.proto.ConfigProto.ConfigResponse.getDefaultInstance() : configResponse_;
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.ConfigResponse config_response = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.ConfigProto.ConfigResponse, com.tt.ocean.proto.ConfigProto.ConfigResponse.Builder, com.tt.ocean.proto.ConfigProto.ConfigResponseOrBuilder> 
          getConfigResponseFieldBuilder() {
        if (configResponseBuilder_ == null) {
          configResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tt.ocean.proto.ConfigProto.ConfigResponse, com.tt.ocean.proto.ConfigProto.ConfigResponse.Builder, com.tt.ocean.proto.ConfigProto.ConfigResponseOrBuilder>(
                  getConfigResponse(),
                  getParentForChildren(),
                  isClean());
          configResponse_ = null;
        }
        return configResponseBuilder_;
      }

      private com.tt.ocean.proto.NodeProto.NodeRequest nodeRequest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.NodeProto.NodeRequest, com.tt.ocean.proto.NodeProto.NodeRequest.Builder, com.tt.ocean.proto.NodeProto.NodeRequestOrBuilder> nodeRequestBuilder_;
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public boolean hasNodeRequest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public com.tt.ocean.proto.NodeProto.NodeRequest getNodeRequest() {
        if (nodeRequestBuilder_ == null) {
          return nodeRequest_ == null ? com.tt.ocean.proto.NodeProto.NodeRequest.getDefaultInstance() : nodeRequest_;
        } else {
          return nodeRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public Builder setNodeRequest(com.tt.ocean.proto.NodeProto.NodeRequest value) {
        if (nodeRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nodeRequest_ = value;
          onChanged();
        } else {
          nodeRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public Builder setNodeRequest(
          com.tt.ocean.proto.NodeProto.NodeRequest.Builder builderForValue) {
        if (nodeRequestBuilder_ == null) {
          nodeRequest_ = builderForValue.build();
          onChanged();
        } else {
          nodeRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public Builder mergeNodeRequest(com.tt.ocean.proto.NodeProto.NodeRequest value) {
        if (nodeRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              nodeRequest_ != null &&
              nodeRequest_ != com.tt.ocean.proto.NodeProto.NodeRequest.getDefaultInstance()) {
            nodeRequest_ =
              com.tt.ocean.proto.NodeProto.NodeRequest.newBuilder(nodeRequest_).mergeFrom(value).buildPartial();
          } else {
            nodeRequest_ = value;
          }
          onChanged();
        } else {
          nodeRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public Builder clearNodeRequest() {
        if (nodeRequestBuilder_ == null) {
          nodeRequest_ = null;
          onChanged();
        } else {
          nodeRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public com.tt.ocean.proto.NodeProto.NodeRequest.Builder getNodeRequestBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getNodeRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      public com.tt.ocean.proto.NodeProto.NodeRequestOrBuilder getNodeRequestOrBuilder() {
        if (nodeRequestBuilder_ != null) {
          return nodeRequestBuilder_.getMessageOrBuilder();
        } else {
          return nodeRequest_ == null ?
              com.tt.ocean.proto.NodeProto.NodeRequest.getDefaultInstance() : nodeRequest_;
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeRequest node_request = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.NodeProto.NodeRequest, com.tt.ocean.proto.NodeProto.NodeRequest.Builder, com.tt.ocean.proto.NodeProto.NodeRequestOrBuilder> 
          getNodeRequestFieldBuilder() {
        if (nodeRequestBuilder_ == null) {
          nodeRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tt.ocean.proto.NodeProto.NodeRequest, com.tt.ocean.proto.NodeProto.NodeRequest.Builder, com.tt.ocean.proto.NodeProto.NodeRequestOrBuilder>(
                  getNodeRequest(),
                  getParentForChildren(),
                  isClean());
          nodeRequest_ = null;
        }
        return nodeRequestBuilder_;
      }

      private com.tt.ocean.proto.NodeProto.NodeResponse nodeResponse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.NodeProto.NodeResponse, com.tt.ocean.proto.NodeProto.NodeResponse.Builder, com.tt.ocean.proto.NodeProto.NodeResponseOrBuilder> nodeResponseBuilder_;
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public boolean hasNodeResponse() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public com.tt.ocean.proto.NodeProto.NodeResponse getNodeResponse() {
        if (nodeResponseBuilder_ == null) {
          return nodeResponse_ == null ? com.tt.ocean.proto.NodeProto.NodeResponse.getDefaultInstance() : nodeResponse_;
        } else {
          return nodeResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public Builder setNodeResponse(com.tt.ocean.proto.NodeProto.NodeResponse value) {
        if (nodeResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nodeResponse_ = value;
          onChanged();
        } else {
          nodeResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public Builder setNodeResponse(
          com.tt.ocean.proto.NodeProto.NodeResponse.Builder builderForValue) {
        if (nodeResponseBuilder_ == null) {
          nodeResponse_ = builderForValue.build();
          onChanged();
        } else {
          nodeResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public Builder mergeNodeResponse(com.tt.ocean.proto.NodeProto.NodeResponse value) {
        if (nodeResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              nodeResponse_ != null &&
              nodeResponse_ != com.tt.ocean.proto.NodeProto.NodeResponse.getDefaultInstance()) {
            nodeResponse_ =
              com.tt.ocean.proto.NodeProto.NodeResponse.newBuilder(nodeResponse_).mergeFrom(value).buildPartial();
          } else {
            nodeResponse_ = value;
          }
          onChanged();
        } else {
          nodeResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public Builder clearNodeResponse() {
        if (nodeResponseBuilder_ == null) {
          nodeResponse_ = null;
          onChanged();
        } else {
          nodeResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public com.tt.ocean.proto.NodeProto.NodeResponse.Builder getNodeResponseBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getNodeResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      public com.tt.ocean.proto.NodeProto.NodeResponseOrBuilder getNodeResponseOrBuilder() {
        if (nodeResponseBuilder_ != null) {
          return nodeResponseBuilder_.getMessageOrBuilder();
        } else {
          return nodeResponse_ == null ?
              com.tt.ocean.proto.NodeProto.NodeResponse.getDefaultInstance() : nodeResponse_;
        }
      }
      /**
       * <code>optional .com.tt.ocean.proto.NodeResponse node_response = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tt.ocean.proto.NodeProto.NodeResponse, com.tt.ocean.proto.NodeProto.NodeResponse.Builder, com.tt.ocean.proto.NodeProto.NodeResponseOrBuilder> 
          getNodeResponseFieldBuilder() {
        if (nodeResponseBuilder_ == null) {
          nodeResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tt.ocean.proto.NodeProto.NodeResponse, com.tt.ocean.proto.NodeProto.NodeResponse.Builder, com.tt.ocean.proto.NodeProto.NodeResponseOrBuilder>(
                  getNodeResponse(),
                  getParentForChildren(),
                  isClean());
          nodeResponse_ = null;
        }
        return nodeResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tt.ocean.proto.OceanMessage)
    }

    // @@protoc_insertion_point(class_scope:com.tt.ocean.proto.OceanMessage)
    private static final com.tt.ocean.proto.OceanProto.OceanMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tt.ocean.proto.OceanProto.OceanMessage();
    }

    public static com.tt.ocean.proto.OceanProto.OceanMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OceanMessage>
        PARSER = new com.google.protobuf.AbstractParser<OceanMessage>() {
      public OceanMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OceanMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OceanMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OceanMessage> getParserForType() {
      return PARSER;
    }

    public com.tt.ocean.proto.OceanProto.OceanMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tt_ocean_proto_OceanMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tt_ocean_proto_OceanMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013ocean.proto\022\022com.tt.ocean.proto\032\rmessa" +
      "ge.proto\032\014config.proto\032\nnode.proto\"\327\002\n\014O" +
      "ceanMessage\022*\n\006header\030\001 \002(\0132\032.com.tt.oce" +
      "an.proto.Header\0223\n\theartbeat\030\006 \001(\0132 .com" +
      ".tt.ocean.proto.HeartbeatReq\0229\n\016config_r" +
      "equest\030\002 \001(\0132!.com.tt.ocean.proto.Config" +
      "Request\022;\n\017config_response\030\003 \001(\0132\".com.t" +
      "t.ocean.proto.ConfigResponse\0225\n\014node_req" +
      "uest\030\004 \001(\0132\037.com.tt.ocean.proto.NodeRequ" +
      "est\0227\n\rnode_response\030\005 \001(\0132 .com.tt.ocea" +
      "n.proto.NodeResponseB \n\022com.tt.ocean.pro" +
      "toB\nOceanProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tt.ocean.proto.MessageProto.getDescriptor(),
          com.tt.ocean.proto.ConfigProto.getDescriptor(),
          com.tt.ocean.proto.NodeProto.getDescriptor(),
        }, assigner);
    internal_static_com_tt_ocean_proto_OceanMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tt_ocean_proto_OceanMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tt_ocean_proto_OceanMessage_descriptor,
        new java.lang.String[] { "Header", "Heartbeat", "ConfigRequest", "ConfigResponse", "NodeRequest", "NodeResponse", });
    com.tt.ocean.proto.MessageProto.getDescriptor();
    com.tt.ocean.proto.ConfigProto.getDescriptor();
    com.tt.ocean.proto.NodeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
